# Generated by Django 5.2.4 on 2025-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub')], max_length=20)),
                ('activity_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('message', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
