# Generated by Django 5.2.4 on 2025-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedactivity',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='feedactivity',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
